### ISSUE TITLE
webpack_require.c might be `undefined`, which will lead to a null pointer exception.

### ISSUE THREAD

**Issue by nanyuantingfeng** [rspack-contrib/rspack-plugin-react-refresh#4]
According to the configuration example, the following issues is: 

<img width="1652" alt="image" src="https://github.com/user-attachments/assets/c407d30a-36dc-4550-90c7-75cd9df1ef08">

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/f8ad7c4f-8e60-42a1-a550-e14d46f99fe8">

adding one line of code  at top of entry point file :  `require.cache = require.cache || {}`, this issue will be fixed.

**Comment by chenjiahan** [comment]
Can you provide a reproduction?

**Comment by phespen** [comment]
Here's an example repo which breaks when running `pnpm start` with the above mentioned error:
https://gitlab.com/hespen/rspack-refresh-example-issue

**Comment by LingyuCoder** [comment]
> Here's an example repo which breaks when running `pnpm start` with the above mentioned error: [gitlab.com/hespen/rspack-refresh-example-issue](https://gitlab.com/hespen/rspack-refresh-example-issue)

Should add `new rspack.HotModuleReplacementPlugin()` to `plugins` when `mode` is "development"

**Comment by phespen** [comment]
That indeed solved the problem!
